using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;

namespace SparrowRunner.Gui
{
    public sealed class SourceScope
    {
        public SourceScope(string rootPath, SourceScopeNode rootNode, int totalFiles, int excludedFiles)
        {
            RootPath = rootPath;
            RootNode = rootNode;
            TotalFiles = totalFiles;
            ExcludedFiles = excludedFiles;
        }

        public string RootPath { get; }
        public SourceScopeNode RootNode { get; }
        public int TotalFiles { get; }
        public int ExcludedFiles { get; }

        public IReadOnlyList<string> SelectedFiles =>
            RootNode.EnumerateSelectedFiles()
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .OrderBy(p => p, StringComparer.OrdinalIgnoreCase)
                .ToList();
    }

    public static class SourceScopeDiscovery
    {
        private static readonly HashSet<string> ExcludedDirectoryNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            ".git", ".vs", "bin", "obj", "packages",
        };

        public static Task<SourceScope> DiscoverAsync(string targetPath, bool includeGenerated, CancellationToken cancellationToken)
        {
            return Task.Run(() => Discover(targetPath, includeGenerated, cancellationToken), cancellationToken);
        }

        private static SourceScope Discover(string targetPath, bool includeGenerated, CancellationToken cancellationToken)
        {
            string targetFull = Path.GetFullPath(targetPath.Trim().Trim('"'));
            if (File.Exists(targetFull) && targetFull.EndsWith(".sln", StringComparison.OrdinalIgnoreCase))
            {
                SourceScope? solutionScope = DiscoverSolution(targetFull, includeGenerated, cancellationToken);
                if (solutionScope != null) return solutionScope;
            }

            if (File.Exists(targetFull) && targetFull.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
            {
                string fileRoot = Path.GetDirectoryName(targetFull) ?? Environment.CurrentDirectory;
                var rootNode = new SourceScopeNode(Path.GetFileName(fileRoot), fileRoot, isFile: false);
                if (includeGenerated || (!IsGeneratedOrBackup(targetFull) && !HasAutoGeneratedHeader(targetFull)))
                {
                    rootNode.Children.Add(new SourceScopeNode(Path.GetFileName(targetFull), targetFull, isFile: true, rootNode));
                    rootNode.RefreshFromChildren();
                    return new SourceScope(fileRoot, rootNode, totalFiles: 1, excludedFiles: 0);
                }

                rootNode.RefreshFromChildren();
                return new SourceScope(fileRoot, rootNode, totalFiles: 1, excludedFiles: 1);
            }

            string rootPath = File.Exists(targetFull)
                ? Path.GetDirectoryName(targetFull) ?? Environment.CurrentDirectory
                : targetFull;
            rootPath = Path.GetFullPath(rootPath);
            if (!Directory.Exists(rootPath)) throw new DirectoryNotFoundException(rootPath);

            var rootInfo = new DirectoryInfo(rootPath);
            var root = new SourceScopeNode(rootInfo.Name.Length == 0 ? rootInfo.FullName : rootInfo.Name, rootInfo.FullName, isFile: false);
            root.IsExpanded = true;
            int total = 0;
            int excluded = 0;
            Populate(rootInfo, root, includeGenerated, ref total, ref excluded, cancellationToken);
            root.RefreshFromChildren();
            return new SourceScope(rootInfo.FullName, root, total, excluded);
        }

        private static SourceScope? DiscoverSolution(string solutionPath, bool includeGenerated, CancellationToken cancellationToken)
        {
            string solutionDir = Path.GetDirectoryName(solutionPath) ?? Environment.CurrentDirectory;
            var projects = ReadSolutionProjects(solutionPath)
                .Select(p => new
                {
                    p.Name,
                    ProjectPath = Path.GetFullPath(Path.Combine(solutionDir, p.RelativePath))
                })
                .Where(p => File.Exists(p.ProjectPath))
                .Select(p => new
                {
                    p.Name,
                    p.ProjectPath,
                    ProjectDir = Path.GetDirectoryName(p.ProjectPath) ?? solutionDir
                })
                .GroupBy(p => p.ProjectPath, StringComparer.OrdinalIgnoreCase)
                .Select(g => g.First())
                .OrderBy(p => p.Name, StringComparer.OrdinalIgnoreCase)
                .ToList();

            if (projects.Count == 0) return null;

            var root = new SourceScopeNode(Path.GetFileNameWithoutExtension(solutionPath), solutionDir, isFile: false)
            {
                IsExpanded = true
            };
            int total = 0;
            int excluded = 0;
            foreach (var project in projects)
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (!Directory.Exists(project.ProjectDir)) continue;

                var projectNode = new SourceScopeNode(project.Name, project.ProjectDir, isFile: false, root);
                Populate(new DirectoryInfo(project.ProjectDir), projectNode, includeGenerated, ref total, ref excluded, cancellationToken);
                if (!projectNode.EnumerateFiles().Any()) continue;

                projectNode.RefreshFromChildren();
                root.Children.Add(projectNode);
            }

            root.RefreshFromChildren();
            return new SourceScope(solutionDir, root, total, excluded);
        }

        private static IEnumerable<(string Name, string RelativePath)> ReadSolutionProjects(string solutionPath)
        {
            var rx = new Regex(
                "^Project\\(\"[^\"]+\"\\)\\s*=\\s*\"(?<name>[^\"]+)\",\\s*\"(?<path>[^\"]+\\.csproj)\"",
                RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
            foreach (string line in File.ReadLines(solutionPath))
            {
                Match match = rx.Match(line);
                if (!match.Success) continue;
                string relativePath = match.Groups["path"].Value;
                if (Path.IsPathRooted(relativePath)) continue;
                yield return (match.Groups["name"].Value, relativePath);
            }
        }

        private static void Populate(DirectoryInfo directory, SourceScopeNode node, bool includeGenerated, ref int total, ref int excluded, CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();

            IEnumerable<DirectoryInfo> directories;
            try
            {
                directories = directory.EnumerateDirectories()
                    .Where(d => !ExcludedDirectoryNames.Contains(d.Name))
                    .OrderBy(d => d.Name, StringComparer.OrdinalIgnoreCase)
                    .ToList();
            }
            catch
            {
                return;
            }

            foreach (DirectoryInfo childDir in directories)
            {
                var child = new SourceScopeNode(childDir.Name, childDir.FullName, isFile: false, node);
                Populate(childDir, child, includeGenerated, ref total, ref excluded, cancellationToken);
                if (child.EnumerateFiles().Any())
                {
                    child.RefreshFromChildren();
                    node.Children.Add(child);
                }
            }

            IEnumerable<FileInfo> files;
            try
            {
                files = directory.EnumerateFiles("*.cs", SearchOption.TopDirectoryOnly)
                    .OrderBy(f => f.Name, StringComparer.OrdinalIgnoreCase)
                    .ToList();
            }
            catch
            {
                return;
            }

            foreach (FileInfo file in files)
            {
                cancellationToken.ThrowIfCancellationRequested();
                total++;
                if (!includeGenerated && (IsGeneratedOrBackup(file.FullName) || HasAutoGeneratedHeader(file.FullName)))
                {
                    excluded++;
                    continue;
                }

                node.Children.Add(new SourceScopeNode(file.Name, file.FullName, isFile: true, node));
            }
        }

        private static bool IsGeneratedOrBackup(string filePath)
        {
            string name = Path.GetFileName(filePath);
            if (name.Equals("AssemblyInfo.cs", StringComparison.OrdinalIgnoreCase)) return true;
            if (name.StartsWith("TemporaryGeneratedFile_", StringComparison.OrdinalIgnoreCase) &&
                name.EndsWith(".cs", StringComparison.OrdinalIgnoreCase)) return true;
            return name.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
                   || name.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)
                   || name.EndsWith(".Designer.cs", StringComparison.OrdinalIgnoreCase)
                   || name.EndsWith(".AssemblyInfo.cs", StringComparison.OrdinalIgnoreCase)
                   || name.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase);
        }

        private static bool HasAutoGeneratedHeader(string filePath)
        {
            try
            {
                using var reader = new StreamReader(filePath, detectEncodingFromByteOrderMarks: true);
                for (int i = 0; i < 4 && !reader.EndOfStream; i++)
                {
                    string? line = reader.ReadLine();
                    if (line != null && line.IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0)
                    {
                        return true;
                    }
                }
            }
            catch
            {
                return false;
            }

            return false;
        }
    }
}
