// 작업 범위 트리 = 대상 루트의 "폴더 구조 그대로". 솔루션(.sln)을 파싱하지 않는다.
//
// 왜 sln 파싱을 걷어냈나(실측):
//   러너는 .sln/.csproj 를 받으면 Split-Path -Parent 로 부모 폴더를 소스 루트로 삼아 그 아래 *.cs 를 전부 훑는다
//   (Run-SparrowSyntaxFix.ps1 / Run-SparrowCommentFix.ps1). 즉 실제 수정 동작에 sln 은 아무 역할이 없다.
//   반면 예전 GUI 는 sln 이 선언한 프로젝트 폴더 아래만 트리에 담았다. 그래서 sln 에 없는 프로젝트·루트 레벨
//   .cs·느슨한 폴더의 .cs 가 트리에 아예 안 보였고, GUI 는 체크된 파일만 --files-from 으로 넘기므로
//   "트리에 안 보이면 영원히 안 고쳐지는" 커버리지 구멍이 됐다.
//   이제 GUI 도 러너와 같은 규칙(부모 폴더 = 루트)을 쓰므로 두 쪽의 대상 집합이 일치한다.
//
// 제외는 종전 그대로다: bin/obj/.git/.vs/packages 디렉토리 + 생성 파일(이름 규칙 · 자동생성 헤더 주석).
// (헤더 주석에 자동생성 표식 문자열 자체를 적지 말 것 — Roslyn 이 이 파일을 생성 코드로 오인해 CS8669 가 난다.)
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace SparrowRunner.Gui
{
    public sealed class SourceScope
    {
        public SourceScope(string rootPath, SourceScopeNode rootNode, int totalFiles, int excludedFiles)
        {
            RootPath = rootPath;
            RootNode = rootNode;
            TotalFiles = totalFiles;
            ExcludedFiles = excludedFiles;
        }

        public string RootPath { get; }
        public SourceScopeNode RootNode { get; }
        public int TotalFiles { get; }
        public int ExcludedFiles { get; }

        public IReadOnlyList<string> SelectedFiles =>
            RootNode.EnumerateSelectedFiles()
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .OrderBy(p => p, StringComparer.OrdinalIgnoreCase)
                .ToList();
    }

    public static class SourceScopeDiscovery
    {
        private static readonly HashSet<string> ExcludedDirectoryNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            ".git", ".vs", "bin", "obj", "packages",
        };

        public static Task<SourceScope> DiscoverAsync(string targetPath, bool includeGenerated, CancellationToken cancellationToken)
        {
            return Task.Run(() => Discover(targetPath, includeGenerated, cancellationToken), cancellationToken);
        }

        private static SourceScope Discover(string targetPath, bool includeGenerated, CancellationToken cancellationToken)
        {
            string targetFull = Path.GetFullPath(targetPath.Trim().Trim('"'));
            if (File.Exists(targetFull) && targetFull.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
            {
                string fileRoot = Path.GetDirectoryName(targetFull) ?? Environment.CurrentDirectory;
                var rootNode = new SourceScopeNode(Path.GetFileName(fileRoot), fileRoot, isFile: false);
                if (includeGenerated || (!IsGeneratedOrBackup(targetFull) && !HasAutoGeneratedHeader(targetFull)))
                {
                    rootNode.Children.Add(new SourceScopeNode(Path.GetFileName(targetFull), targetFull, isFile: true, rootNode));
                    rootNode.RefreshFromChildren();
                    return new SourceScope(fileRoot, rootNode, totalFiles: 1, excludedFiles: 0);
                }

                rootNode.RefreshFromChildren();
                return new SourceScope(fileRoot, rootNode, totalFiles: 1, excludedFiles: 1);
            }

            // .sln/.csproj 등 파일을 받으면 그 '부모 폴더'가 루트다 — 러너의 Split-Path -Parent 와 같은 규칙.
            // 폴더를 받으면 그대로 루트. 어느 폴더를 고를지는 사용자 몫이며 여기서 더 좁히지 않는다.
            string rootPath = File.Exists(targetFull)
                ? Path.GetDirectoryName(targetFull) ?? Environment.CurrentDirectory
                : targetFull;
            rootPath = Path.GetFullPath(rootPath);
            if (!Directory.Exists(rootPath)) throw new DirectoryNotFoundException(rootPath);

            var rootInfo = new DirectoryInfo(rootPath);
            var root = new SourceScopeNode(rootInfo.Name.Length == 0 ? rootInfo.FullName : rootInfo.Name, rootInfo.FullName, isFile: false);
            root.IsExpanded = true;
            int total = 0;
            int excluded = 0;
            Populate(rootInfo, root, includeGenerated, ref total, ref excluded, cancellationToken);
            root.RefreshFromChildren();
            return new SourceScope(rootInfo.FullName, root, total, excluded);
        }

        private static void Populate(DirectoryInfo directory, SourceScopeNode node, bool includeGenerated, ref int total, ref int excluded, CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();

            IEnumerable<DirectoryInfo> directories;
            try
            {
                directories = directory.EnumerateDirectories()
                    .Where(d => !ExcludedDirectoryNames.Contains(d.Name))
                    .OrderBy(d => d.Name, StringComparer.OrdinalIgnoreCase)
                    .ToList();
            }
            catch
            {
                return;
            }

            foreach (DirectoryInfo childDir in directories)
            {
                var child = new SourceScopeNode(childDir.Name, childDir.FullName, isFile: false, node);
                Populate(childDir, child, includeGenerated, ref total, ref excluded, cancellationToken);
                if (child.EnumerateFiles().Any())
                {
                    child.RefreshFromChildren();
                    node.Children.Add(child);
                }
            }

            IEnumerable<FileInfo> files;
            try
            {
                files = directory.EnumerateFiles("*.cs", SearchOption.TopDirectoryOnly)
                    .OrderBy(f => f.Name, StringComparer.OrdinalIgnoreCase)
                    .ToList();
            }
            catch
            {
                return;
            }

            foreach (FileInfo file in files)
            {
                cancellationToken.ThrowIfCancellationRequested();
                total++;
                if (!includeGenerated && (IsGeneratedOrBackup(file.FullName) || HasAutoGeneratedHeader(file.FullName)))
                {
                    excluded++;
                    continue;
                }

                node.Children.Add(new SourceScopeNode(file.Name, file.FullName, isFile: true, node));
            }
        }

        private static bool IsGeneratedOrBackup(string filePath)
        {
            string name = Path.GetFileName(filePath);
            if (name.Equals("AssemblyInfo.cs", StringComparison.OrdinalIgnoreCase)) return true;
            if (name.StartsWith("TemporaryGeneratedFile_", StringComparison.OrdinalIgnoreCase) &&
                name.EndsWith(".cs", StringComparison.OrdinalIgnoreCase)) return true;
            return name.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
                   || name.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)
                   || name.EndsWith(".Designer.cs", StringComparison.OrdinalIgnoreCase)
                   || name.EndsWith(".AssemblyInfo.cs", StringComparison.OrdinalIgnoreCase)
                   || name.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase);
        }

        private static bool HasAutoGeneratedHeader(string filePath)
        {
            try
            {
                using var reader = new StreamReader(filePath, detectEncodingFromByteOrderMarks: true);
                for (int i = 0; i < 4 && !reader.EndOfStream; i++)
                {
                    string? line = reader.ReadLine();
                    if (line != null && line.IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0)
                    {
                        return true;
                    }
                }
            }
            catch
            {
                return false;
            }

            return false;
        }
    }
}
