<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>SparrowCFamilySyntaxFix</AssemblyName>
    <RootNamespace>SparrowCFamilySyntaxFix</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SparrowCFamily.Core\SparrowCFamily.Core.csproj" />
  </ItemGroup>

</Project>
