// File discovery + the generated/backup exclusion filter, plus a small CSV reader for --files-from.
//
// Given a directory, recurse for *.cs. EXCLUDE generated/backup files by default (they inflate counts and
// must not be edited): *.Designer.cs, *.g.cs, *.g.i.cs, *.AssemblyInfo.cs, AssemblyInfo.cs,
// TemporaryGeneratedFile_*.cs, *.generated.cs, and any file whose first ~3 lines contain `<auto-generated`.
//
// --files-from reads target paths from the pipeline's index.csv (mirrors SparrowXlsExport's CSV quoting):
// it prefers a column named 파일명, then a path-like column; a plain newline-delimited list also works.
// Relative paths resolve against --root.

using System;
using System.Collections.Generic;
using System.IO;

namespace SparrowSyntaxFix
{
    internal static class FileDiscovery
    {
        private static readonly string[] ExcludedSuffixes =
        {
            ".Designer.cs", ".g.cs", ".g.i.cs", ".AssemblyInfo.cs", ".generated.cs",
        };

        // Header names to look for in a --files-from CSV, in priority order (파일명 first, then path-like).
        private static readonly string[] HeaderNames = { "파일명", "경로", "path", "filepath", "file" };

        // Name-based generated/backup filter.
        public static bool IsGeneratedName(string fileName)
        {
            if (string.Equals(fileName, "AssemblyInfo.cs", StringComparison.OrdinalIgnoreCase)) return true;
            if (fileName.StartsWith("TemporaryGeneratedFile_", StringComparison.OrdinalIgnoreCase)
                && fileName.EndsWith(".cs", StringComparison.OrdinalIgnoreCase)) return true;
            foreach (string s in ExcludedSuffixes)
                if (fileName.EndsWith(s, StringComparison.OrdinalIgnoreCase)) return true;
            return false;
        }

        // First ~3 lines contain an `<auto-generated` marker (case-insensitive).
        public static bool HasAutoGeneratedHeader(string text)
        {
            int line = 0, i = 0;
            while (line < 3 && i < text.Length)
            {
                int nl = text.IndexOf('\n', i);
                string chunk = nl < 0 ? text.Substring(i) : text.Substring(i, nl - i);
                if (chunk.IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0) return true;
                if (nl < 0) break;
                i = nl + 1;
                line++;
            }
            return false;
        }

        // Expand explicit targets (files/dirs) into a sorted, de-duplicated full-path .cs list. Directories
        // recurse for *.cs. A target that does not exist is reported via onMissing (caller decides fatal).
        public static List<string> ExpandTargets(IEnumerable<string> targets, string root, Action<string> onMissing)
        {
            var set = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var ordered = new List<string>();

            void Add(string p)
            {
                string full = Path.GetFullPath(p);
                if (set.Add(full)) ordered.Add(full);
            }

            foreach (string t in targets)
            {
                string resolved = Path.IsPathRooted(t) ? t : Path.Combine(root, t);
                if (Directory.Exists(resolved))
                {
                    foreach (string f in Directory.EnumerateFiles(resolved, "*.cs", SearchOption.AllDirectories))
                        Add(f);
                }
                else if (File.Exists(resolved))
                {
                    if (resolved.EndsWith(".cs", StringComparison.OrdinalIgnoreCase)) Add(resolved);
                }
                else
                {
                    onMissing(Path.GetFullPath(resolved));
                }
            }

            ordered.Sort(StringComparer.OrdinalIgnoreCase);
            return ordered;
        }

        // Read target .cs paths from a CSV (파일명/path column) or a newline-delimited list. Relative paths
        // resolve against root. A referenced file that is absent is reported via onMissing (warn+skip).
        public static List<string> FromIndex(string indexPath, string root, Action<string> onMissing)
        {
            var result = new List<string>();
            var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            List<string[]> rows = Csv.Parse(File.ReadAllText(indexPath));
            if (rows.Count == 0) return result;

            int col = PickColumn(rows[0]);
            int startRow = 0;
            if (col >= 0 && col < rows[0].Length && IsHeaderCell(rows[0][col].Trim())) startRow = 1;
            if (col < 0) col = 0;   // multi-column with no recognizable header: fall back to the first column

            for (int r = startRow; r < rows.Count; r++)
            {
                if (col >= rows[r].Length) continue;
                string cell = rows[r][col].Trim();
                if (cell.Length == 0) continue;

                string resolved = Path.IsPathRooted(cell) ? cell : Path.Combine(root, cell);
                resolved = Path.GetFullPath(resolved);
                if (!seen.Add(resolved)) continue;
                if (!File.Exists(resolved)) { onMissing(resolved); continue; }
                if (!resolved.EndsWith(".cs", StringComparison.OrdinalIgnoreCase)) continue;
                result.Add(resolved);
            }

            result.Sort(StringComparer.OrdinalIgnoreCase);
            return result;
        }

        private static int PickColumn(string[] header)
        {
            foreach (string name in HeaderNames)
                for (int c = 0; c < header.Length; c++)
                    if (string.Equals(header[c].Trim(), name, StringComparison.OrdinalIgnoreCase))
                        return c;
            return header.Length == 1 ? 0 : -1;
        }

        private static bool IsHeaderCell(string cell)
        {
            foreach (string name in HeaderNames)
                if (string.Equals(cell, name, StringComparison.OrdinalIgnoreCase)) return true;
            return false;
        }
    }
}
